### ISSUE TITLE
failed to read from foundry-config.json

### ISSUE THREAD

**Issue by kevinweaver** [base-org/contract-deployments#89] opened 2023-08-16 18:27 UTC
## Reproduction steps
Follow the steps outlined in the readme to create a new deployment.

It will result in:
```
failed to read from "/contract-deployments/mainnet/2023-06-14-deploy/inputs/foundry-config.json": No such file or directory (os error 2)
```

This is not a standard foundry file, the docs do not suggest creating one, and I don't see it attempting to be created in the script.

This also occurs when you attempt to re-run the first, already existing deployment in the mainnet folder

**Comment by anikaraghu** [comment] 2023-08-31 15:22
@kevinweaver sorry for the delay here - could you list the steps you ran? I was not able to reproduce this issue. In the deploy command it runs `go run cmd/foundry_deploy_config_gen/main.go` which generates that `foundry-config.json` file you mentioned. I did however run into a different issue in running these steps, which I have put a PR to fix here: https://github.com/base-org/contract-deployments/pull/102

**Comment by anikaraghu** [comment] 2023-09-15 01:36
Marking this as resolved since the PR which fixed local deploys for me is now merged. Feel free to reopen if the issue persists

**Closed by anikaraghu** 2023-09-15 01:36 UTC
